### ISSUE TITLE
Check possibilities for k8s-tools autobump

### ISSUE THREAD

**Issue by Halamix2** [kyma-project/third-party-images#210]
**Description**

- [x] automate Alpine version bump with dependabot (#207)
- [ ] Check if we can autobump kubectl in `k8s-tools` image

**Reasons**

k8s-tools image only requires occasional version bump, which could be automated
**Attachments**

**Comment by tillknuesting** [comment]
push

**Comment by Halamix2** [comment]
* we can't automatically update minor version, only patch version, to not break K8S compatibility
* patch version rarely contains updated Golang dependecies
